"""Push the branch and open a draft PR via the GitHub App.

Rules: PR is always draft=True. JARVIS never merges (auto_merge is always
False - nothing in this module ever calls merge()).
"""
from __future__ import annotations

from datetime import datetime, timezone

from jarvis.clients.github_client import GitHubClient
from jarvis.config import JarvisConfig
from jarvis.models.code_change import CodeChange
from jarvis.models.plan import Plan
from jarvis.models.pr_result import PullRequestResult
from jarvis.models.review import ReviewResult
from jarvis.models.test_result import TestResult
from jarvis.models.ticket import JiraTicket, priority_label

_MAX_STDOUT_CHARS = 3000


def create_pr(
    ticket: JiraTicket,
    repo_full_name: str,
    change: CodeChange,
    test_result: TestResult,
    review_result: ReviewResult,
    approver: str,
    artifact_key: str,
    config: JarvisConfig,
    *,
    run_id: str,
    plan: Plan,
    duration_seconds: float,
    state_log: list[str],
) -> PullRequestResult:
    client = GitHubClient(config.github)
    branch = f"{config.git.branch_prefix}{ticket.key.lower()}"

    client.push_branch_with_files(
        repo_full_name=repo_full_name,
        branch=branch,
        base_branch=config.git.base_branch,
        files=change.files,
        commit_message=f"{ticket.key}: JARVIS code change",
    )

    body = build_pr_body(
        ticket=ticket,
        change=change,
        test_result=test_result,
        review_result=review_result,
        approver=approver,
        config=config,
        run_id=run_id,
        plan=plan,
        duration_seconds=duration_seconds,
        state_log=state_log,
    )
    url = client.open_draft_pr(
        repo_full_name=repo_full_name,
        branch=branch,
        base_branch=config.git.base_branch,
        title=f"{ticket.key}: {ticket.summary}",
        body=body,
    )

    return PullRequestResult(url=url, branch=branch)


def build_pr_body(
    *,
    ticket: JiraTicket,
    change: CodeChange,
    test_result: TestResult,
    review_result: ReviewResult,
    approver: str,
    config: JarvisConfig,
    run_id: str,
    plan: Plan,
    duration_seconds: float,
    state_log: list[str],
) -> str:
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    models = config.models
    files_table = "\n".join(
        ["| Path | Reason |", "|---|---|"]
        + [f"| `{fc.path}` | {_cell(fc.reason)} |" for fc in plan.files_to_change]
    )
    changed_files = "\n".join(f"- `{path}`" for path in (change.files_changed or list(change.files))) or "(none)"
    state_lines = "\n".join(f"{n}. {entry}" for n, entry in enumerate(state_log, start=1))
    test_status = "✅ passed" if test_result.passed else "❌ failed"

    return f"""## JARVIS Run — {ticket.key}

**Ticket:** [{ticket.key}] {ticket.summary}
**Priorität / Priority:** {priority_label(ticket.priority) or "–"}
**Run ID:** {run_id}
**Date:** {date}
**Plan approved by:** {approver}
**Total duration:** {duration_seconds:.1f}s

---

### Models used
| Role | Model | Latency |
|---|---|---|
| Planner | {models.planner} | {plan.latency_seconds:.1f}s |
| Coder | {models.coder} | {change.latency_seconds:.1f}s |
| Reviewer | {models.reviewer} | {review_result.latency_seconds:.1f}s |

---

### Plan (approved)
**Approach:** {plan.approach}

**Files to change:**
{files_table}

**Risk class:** {plan.risk_class}

---

### Test results
**Status:** {test_status}
**Exit code:** {test_result.exit_code}
**Tests passed:** {test_result.passed_count}
**Tests failed:** {test_result.failed}
**Duration:** {test_result.duration_seconds:.1f}s

```text
{_truncate(test_result.stdout.strip())}
```

---

### Judge review (jarvis-review / laaj-judge:v2)
{review_result.findings}

---

### Files changed
{changed_files}

---

### Run log
**State transitions:**
{state_lines}

**Artifacts:** stored in MinIO under `runs/{run_id}/`

---
*Generated by JARVIS V0 — WAMOCON internal AI development agent*
*This PR was opened automatically. A human must review and merge.*
*JARVIS never merges. auto_merge = False.*
"""


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _truncate(text: str) -> str:
    if len(text) <= _MAX_STDOUT_CHARS:
        return text
    return text[:_MAX_STDOUT_CHARS] + "\n... (truncated)"
